import { Company } from "@/lib/types";

// Auto-generated by scripts/generate_listed_companies.py
// Keep this file committed after generation so the app can use the full list.
export const generatedCompanies: Company[] = [];
